links:
  rails_tutorial:
    help_page: http://www.railstutorial.org/help
    book_page: https://www.railstutorial.org/book
    home_page: http://www.railstutorial.org/
    screencast_page: https://screencasts.railstutorial.org/
    learnenough_page: https://www.learnenough.com/
    news_page: https://news.railstutorial.org/
    michaelhartl_page: "https://www.michaelhartl.com/"
    contact_page: "https://www.railstutorial.org/contact"
